
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJNQVJJQU5FIiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfTUFOQUdFUiIsIlJPTEVfU1VQRVJfQURNSU4iXSwiaXNzIjoiL2FwaS9sb2dpbiIsImV4cCI6MTY1Nzc4MDQzMH0.0ouIBkgSRLvFEo9H7FY5qeY7en8EnuBApi2jI1u-JIc

@content-type-form = application/x-www-form-urlencoded

@content-type-json = application/json

###

GET http://localhost:8080/api/ceps/importacaoCEP HTTP/1.1
content-type: {{content-type-json}}
Authorization: Bearer {{token}}

###


GET http://localhost:8080/api/ceps/uf HTTP/1.1
content-type: {{content-type-json}}
Authorization: Bearer {{token}}

###

GET http://localhost:8080/api/ceps/localidade/RJ HTTP/1.1
content-type: {{content-type-json}}
Authorization: Bearer {{token}}

###

GET http://localhost:8080/api/ceps/bairro/7043 HTTP/1.1
content-type: {{content-type-json}}
Authorization: Bearer {{token}}

###

GET http://localhost:8080/api/ceps/pesquisar/07240090 HTTP/1.1
content-type: {{content-type-json}}
Authorization: Bearer {{token}}

###


GET http://localhost:8080/api/ceps/pesquisarLog/AFONSO HTTP/1.1
content-type: {{content-type-json}}
Authorization: Bearer {{token}}

###