
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJNQVJJQU5FIiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfTUFOQUdFUiIsIlJPTEVfU1VQRVJfQURNSU4iXSwiaXNzIjoiL2FwaS9sb2dpbiIsImV4cCI6MTY1NDc3MDIyNX0.TwK0S6zzR_kyL2Jp3XiWVxTzm104a5dY83LCJcNvAJk
@content-type-form = application/x-www-form-urlencoded
@content-type-json = application/json
###

GET http://localhost:8080/api/enderecos/paged?idPessoa=1 HTTP/1.1
content-type: {{content-type-json}}
Authorization: Bearer {{token}}
###

GET http://localhost:8080/api/enderecos/1 HTTP/1.1
content-type: {{content-type-json}}
Authorization: Bearer {{token}}
###

POST http://localhost:8080/api/enderecos HTTP/1.1
content-type: {{content-type-json}}
Authorization: Bearer {{token}}

[{
    "pessoa": {
      "id": 1
    },
    "logradouro": "rua moura brito"
},{
    "pessoa": {
      "id": 1
    },
    "logradouro": "rua pirenopolis"
}]
###

PUT http://localhost:8080/api/enderecos/1 HTTP/1.1
content-type: {{content-type-json}}
Authorization: Bearer {{token}}

{
  "id": 1,
  "cep": null,
  "logradouro": "rua afonço cunha",
  "principal": false,
  "numero": null,
  "complemento": null,
  "uf": null,
  "cidade": null,
  "bairro": null,
  "tipo": null,
  "pessoa": {
    "id": 1
  }
}